# Generated by Django 4.2.5 on 2023-10-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlocation",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="latitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="longitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
