# Generated by Django 4.2.5 on 2023-10-05 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ["time"]},
        ),
    ]
