# Generated by Django 4.2.5 on 2023-09-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="address",
            field=models.CharField(default="서울시", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
