# Generated by Django 4.2.5 on 2023-09-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_plan_address_alter_plan_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="latitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="longitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
