# Generated by Django 4.2.5 on 2023-10-06 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-id"]},
        ),
    ]
