# Generated by Django 4.2.5 on 2023-10-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0005_category_plan_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default=1, max_length=200, unique=True
            ),
            preserve_default=False,
        ),
    ]
